Тултип, для PR
js-tasks-ru/htmlcss-20220120_alaudo-galkin pull request #8
Opened 2022-02-08 11:48 UTC by alaudo

Тултип, вид на hover:
![image](https://user-images.githubusercontent.com/166919/152981213-43002393-efe5-489c-9d88-14d5e9154580.png)

2022-02-08 11:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-08 12:40 UTC, GSemikozov requested changes

2022-02-08 12:40 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    left:0;
всегда слева 0?
скорее имелось в виду 50%&
и еще - для позиционирования по вертикали желательно задать либо bottom: 0 либо top: 100% (+ через calc можно этим управлять). И в таком случае не нужен будет ни марджин снизу, ни translateY (здесь transform: translate(-50%,-50%))

2022-02-08 15:32 UTC, alaudo commented on 05-lection3/01-tooltip/tooltip.css
> +    left:0;
Тут я просто сначала пытался спозиционировать их как inline-flex и использовать align-items, но не получилось, с той попытки остались такие границы, поправил.
Почему-то упорно не работало calc(100% - 1px), но когда попробовал calc(100% - 2px) вдруг неожиданно сработало. Немного странно.

2022-02-08 20:06 UTC, GSemikozov requested changes

2022-02-08 20:06 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%,-50%);
кажется, -50% по вертикали это лишнее (просто сдвинет на половину размера стрелки). Если уже указываем фиксированное значение bottom: 15px, то проще именно это значение разделить на 2 (15 / 2 = ~8) и не использовать translateY

2022-02-09 00:31 UTC, alaudo commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%,-50%);
Переделал так, заодно чуть поправил SVG.

2022-02-09 16:39 UTC, GSemikozov approved these changes

2022-02-09 16:39 UTC, merged